version: '3.3'

services:
  web_ngoldack:
    image: klakegg/hugo
    networks:
      - proxy
    restart: unless-stopped
    volumes:
        - .:/src
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-ntec.rule=Host(`ntec.io`, `www.ntec.io`)"
        - "traefik.http.routers.web-ntec.entrypoints=http"
        - "traefik.http.middlewares.web-ntec-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.web-ntec.middlewares=web-ntec-https-redirect"
        - "traefik.http.services.web-ntec.loadbalancer.server.port=80"
        - "traefik.http.routers.web-ntec-secure.rule=Host(`ntec.io`, `www.ntec.io`)"
        - "traefik.http.routers.web-ntec-secure.entrypoints=https"
        - "traefik.http.routers.web-ntec-secure.tls.certresolver=http"
        - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true