name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Copy docker compose
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            port: ${{ secrets.PORT }}
            password: ${{ secrets.PASSWORD }}
            #key: ${{ secrets.KEY }}
            source: "docker-compose.yml"
            target: "/opt/docker/ntec.io"

      - name: Copy website files
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            port: ${{ secrets.PORT }}
            password: ${{ secrets.PASSWORD }}
            #key: ${{ secrets.KEY }}
            source: "public/*"
            target: "/opt/docker/ntec.io"

      - name: Starting container
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            #key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: docker-compose -f /opt/docker/ntec.io/docker-compose.yml up -d
