name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Deploy to Docker
        uses: wshihadeh/docker-deployment-action@v1
        with:
            remote_docker_host: ${{ secrets.DOCKER_DEPLOY_USERNAME }}@ntec.io
            ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
            ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
            deployment_mode: docker-compose
            copy_stack_file: true
            deploy_path: ${{ secrets.DOCKER_DEPLOY_BASEPATH }}/ntec.io
            stack_file_name: docker-compose.yaml
            # keep_files: 5
            args: up -d